### ISSUE TITLE
scriptsafe doesn't block anything after update 

### ISSUE THREAD

**Issue by John151** [andryou/scriptsafe#36]
Says 
"ScriptSafe was recently updated/reloaded.

You will need to either refresh this tab, create a new tab, or restart your browser in order for ScriptSafe to work."

I've restarted the browser, the computer, disabled and re-enabled. 
If I go to "options" i can check boxes but clicking "save" doesn't do anything. Using Chromium Version 38.0.2125.111 Ubuntu 14.04 (290379) (64-bit)

**Comment by andryou** [comment]
In the Options page, could you press F12 and copy and paste any console
error messages here? As well as the background page (go to the Chrome
extensions list page and click on the background page for ScriptSafe.
Thanks!

**Comment by John151** [comment]
options page:
Uncaught TypeError: undefined is not a function       options.js:132

background page:
Uncaught SyntaxError: Use of const in strict mode.     scriptsafe.js:12

**Comment by andryou** [comment]
Thanks! If you could, could you help test out the fix I've just committed? I'd really appreciate it!

1. Download a ZIP of the latest code here: https://github.com/andryou/scriptsafe (click on **Clone or download** then **Download ZIP**)
2. Extract the ZIP file to its own folder anywhere on your computer
3. Copy and paste **chrome://extensions** into your browser address bar and press Enter
  * Make sure you have disabled the Chrome Web Store version of ScriptSafe (ID: oiigbmnaadbkfbmpbfijlflahbdbdgdf)
4. Enable "**Developer Mode**
5. Click on **Load unpacked extension**, navigate to the folder you extracted ScriptSafe to in step #2 and click on OK

Please let me know if you have any questions.

**Comment by andryou** [comment]
Installed Mint and Chromium in a virtual machine, was able to reproduce the reported bug and confirmed the fix works. Will push out an update soon as this is an important bug.

**Comment by andryou** [comment]
v1.0.7.10 has been published which should fix this issue. Please close this issue if it's fixed for you :)

**Comment by belgacea** [comment]
Hi andryou,
Unfortunately, ScriptSafe v1.0.7.7 and earlier no longer block any script for me either.
I tried to get back the magic (updating ScriptSafe to v1.0.7.10, Chromium & Chrome, rebooting) but nothing works and i don't know where to find previous version..
Too bad that a nice tool like this is broken :/

**Comment by andryou** [comment]
@belgacea thanks for the info; can you follow the steps I posted here (https://github.com/andryou/scriptsafe/issues/36#issuecomment-225059870) and let me know what error messages (if any) you see?

**Comment by incognico** [comment]
Same Problem, v1.0.7.10 does not fix the issue. options.js:5 says: Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/. - It's a warning not an error though. Using Chrome 52.0.2743.33 beta-m (64-bit). On all pages scriptsafe appears like 
![ss](https://cloud.githubusercontent.com/assets/2098066/15984541/40f47708-2fcf-11e6-9b54-d8ccba72a60a.png)

**Comment by andryou** [comment]
@incognico @John151 @belgacea could you please try this test version?

https://dl.dropboxusercontent.com/u/784305/scriptsafe-20160611-test.zip

For instructions, skip to #2 in the second set of steps on https://github.com/andryou/scriptsafe/wiki/Frequently-Asked-Questions#how-do-i-install-the-latest-version

**Comment by incognico** [comment]
Works for me!

**Comment by belgacea** [comment]
Power is back :)
Nice job, fix done !

**Comment by John151** [comment]
Works great, thank you!

**Comment by andryou** [comment]
Thank you all for the fast replies! Going to spend this weekend testing this fix and other updates out, and push out a release on Monday as I want to avoid stepping on people's toes by pushing out a release every day or every other day. In the meantime, the repo on here contains the fix.

Thank you all for your patience and help.

**Comment by andryou** [comment]
@John151 @belgacea @incognico if you all don't mind, could you help test the beta release I've just posted? https://github.com/andryou/scriptsafe/issues/40

Much appreciated!
